server.port: 8081

server.tomcat.accesslog.enabled: true
server.tomcat.basedir: logs/tomcat

spring.jpa.properties.javax.persistence.validation.mode: none

spring.jpa.hibernate.ddl-auto: update

spring:
  jpa:
    show-sql: true
